Funiture_Project/Controllers/PaymentController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Funiture_Project.Models;
using Funiture_Project.ModelViews;
using Funiture_Project.Extensions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using AspNetCoreHero.ToastNotification.Notyf;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;


namespace Funiture_Project.Controllers
{
    public class PaymentController : Controller
    {
        /*public IActionResult Index()
        {
            return View();
        }*/

        private readonly FurnitureContext _context;
        public INotyfService _notyfService { get; }
        public PaymentController(FurnitureContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }
        
        public IActionResult Index()
        {
            int makh = int.Parse(HttpContext.Session.GetString("MaKH"));
            KhachHang khachhang = _context.KhachHang.AsNoTracking()
                    .Where(x => x.MaKh == makh)
                    .FirstOrDefault();
            List<SanPham> lsSanPham = new List<SanPham>();
            var giohang = _context.GioHang.AsNoTracking()
                .Where(x => x.MaKh == makh)
                .ToList();

            double tong = 0;

            foreach (var item in giohang)
            {
                var sanpham = _context.SanPham.AsNoTracking()
                    .Where(x => x.MaSp == item.MaSp)
                    .FirstOrDefault();
                if (item.SoLuong <= sanpham.TongSl)
                {
                    sanpham.TongSl = item.SoLuong;
                    lsSanPham.Add(sanpham);
                    tong += sanpham.Gia * sanpham.TongSl;
                }
                else
                {
                    sanpham.TongSl = 0;
                }
            }
            if (lsSanPham.Count == 0)
            {
                _notyfService.Error("Đơn hàng rỗng");
                return RedirectToAction("Index", "CartInfo");
            }
            ViewBag.lsSanPham = lsSanPham;
            ViewBag.KhachHang = khachhang;
            ViewBag.TongThanhTien = tong;
            return View();
        }

        //public IActionResult InsertHoaDon()
        //{
        //    int makh = int.Parse(HttpContext.Session.GetString("MaKH"));
        //    var khachhang = _context.KhachHang.AsNoTracking()
        //            .Where(x => x.MaKh == makh)
        //            .FirstOrDefault();
        //    var giohang = _context.GioHang.AsNoTracking()
        //        .Where(x => x.MaKh == makh);
        //    if (giohang != null)
        //    {
        //        //public int MaHd { get; set; }
        //        //public string Ttdh { get; set; }
        //        //public string Tttt { get; set; }
        //        //public int MaKh { get; set; }
        //        //public int MaNv { get; set; }
        //        //public DateTime NgayHd { get; set; }
        //        //public DateTime NgayGh { get; set; }
        //        //public string Sdt { get; set; }
        //        //public string DiaChi { get; set; }
        //        //public string ThanhPho { get; set; }
        //        //public int? MaKm { get; set; }
        //        //public double TriGia { get; set; }
        //        //DateTime today = DateTime.Today();
        //        var new_hoadon = new HoaDon
        //        {
        //            MaKh = makh,
        //            Ttdh = "Đang giao",
        //            Tttt = "Chưa thanh toán",
        //            DiaChi = khachhang.DiaChi,
        //            NgayHd = DateTime.Now,
        //            NgayGh = DateTime.Now,
        //            ThanhPho = khachhang.ThanhPho
        //        };
        //        _context.HoaDon.Add(new_hoadon);
        //        _context.SaveChanges();

        //        var mahd = _context.HoaDon.AsNoTracking()
        //            .OrderByDescending(x => x.MaHd)
        //            .Select(x => x.MaHd)
        //            .FirstOrDefault();
        //        double thanhtien = 0;
        //        foreach (var item in giohang)
        //        {
        //            var sanpham = _context.SanPham.AsNoTracking()
        //                .Where(x => x.MaSp == item.MaSp)
        //                .FirstOrDefault();
        //            var new_cthd = new Cthd
        //            {
        //                MaHd = mahd,
        //                MaSp = item.MaSp,
        //                SoLuong = item.SoLuong,
        //                DonGia = sanpham.Gia
        //            };
        //            thanhtien += new_cthd.DonGia * new_cthd.SoLuong;

        //            _context.Cthd.Add(new_cthd);
        //            var gh = _context.GioHang.AsNoTracking()
        //                .Where(x => x.MaSp == item.MaSp && x.MaKh == makh);
        //            _context.GioHang.Remove(item);
        //        }
        //        new_hoadon.TriGia = thanhtien;
        //        _context.HoaDon.Update(new_hoadon);
        //        _context.SaveChanges();
        //        _notyfService.Success("Đặt hàng thành công");
        //        return RedirectToAction("Index", "Home");
        //    }

        //    return View();
        //}
        [Route("/Payment/InsertHoaDon")]
        public IActionResult InsertHoaDon()
        {
            int makh = int.Parse(HttpContext.Session.GetString("MaKH"));
            var khachhang = _context.KhachHang.AsNoTracking()
                    .Where(x => x.MaKh == makh)
                    .FirstOrDefault();
            //public int MaHd { get; set; }
            //public string Ttdh { get; set; }
            //public string Tttt { get; set; }
            //public int MaKh { get; set; }
            //public int MaNv { get; set; }
            //public DateTime NgayHd { get; set; }
            //public DateTime NgayGh { get; set; }
            //public string Sdt { get; set; }
            //public string DiaChi { get; set; }
            //public string ThanhPho { get; set; }
            //public int? MaKm { get; set; }
            //public double TriGia { get; set; }
            //DateTime today = DateTime.Today();
            var new_hoadon = new HoaDon
            {
                MaKh = makh,
                Ttdh = "Đang giao",
                Tttt = "Chưa thanh toán",
                DiaChi = khachhang.DiaChi,
                Sdt = khachhang.Sdt,
                NgayHd = DateTime.Now,
                NgayGh = DateTime.Now,
                ThanhPho = khachhang.ThanhPho
            };
            _context.HoaDon.Add(new_hoadon);
            _context.SaveChanges();
            var mahd = _context.HoaDon.AsNoTracking()
                .OrderByDescending(x => x.MaHd)
                .Select(x => x.MaHd)
                .FirstOrDefault();
            double thanhtien = 0;
            var giohang = _context.GioHang.AsNoTracking()
                .Where(x => x.MaKh == makh).ToList();
            foreach (var item in giohang)
            {
                var sanpham = _context.SanPham.AsNoTracking()
                    .Where(x => x.MaSp == item.MaSp)
                    .FirstOrDefault();
                if (sanpham.TongSl > item.SoLuong)
                {
                    var new_cthd = new Cthd
                    {
                        MaHd = mahd,
                        MaSp = item.MaSp,
                        SoLuong = item.SoLuong,
                        DonGia = sanpham.Gia
                    };
                    thanhtien += new_cthd.DonGia * new_cthd.SoLuong;

                    _context.Cthd.Add(new_cthd);
                    var gh = _context.GioHang.AsNoTracking()
                        .Where(x => x.MaSp == item.MaSp && x.MaKh == makh);

                    sanpham.TongSl -= item.SoLuong;
                    _context.SanPham.Update(sanpham);

                    _context.GioHang.Remove(item);
                }

            }
            new_hoadon.TriGia = thanhtien;
            _context.HoaDon.Update(new_hoadon);
            _context.SaveChanges();
            _notyfService.Success("Đặt hàng thành công");
            return RedirectToAction("Index", "Home");

        }

    }
}

Funiture_Project/Views/Payment/Index.cshtml
@using Funiture_Project.Models;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    KhachHang khachang = ViewBag.KhachHang;
    List<SanPham> lsSanPham = ViewBag.lsSanPham;
    double tongThanhTien = ViewBag.TongThanhTien;
}
<link href="~/css/slider-product.css" rel="stylesheet" />

<main class="container p-0">
    <div class="mt-[50px] lg:mt-[128px] mb-[50px] flex items-center justify-center flex-col gap-y-[40px]">
        <h1 class="text-[26px] lg:text-[64px] font-bold">Thanh toán</h1>
        <div class="flex items-center justify-center w-full flex-col gap-y-[20px]">
            <div class="w-full flex items-center justify-center w-full flex-col p-5 lg:px-[46px] lg:py-[18px] border border-[rgba(21,20,17,0.7)] lg:gap-y-5">
                <span class="w-full flex items-center justify-center gap-x-2 lg:gap-x-0 text-[#FFB23F] font-medium">
                    <div class="w-[24px] lg:w-[70px]">
                        <svg width="28" height="37" viewBox="0 0 28 37" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M15.7281 36.075C19.4688 31.4355 28 20.191 28 13.875C28 6.21484 21.7292 0 14 0C6.27083 0 0 6.21484 0 13.875C0 20.191 8.53125 31.4355 12.2719 36.075C13.1687 37.1807 14.8312 37.1807 15.7281 36.075ZM14 18.5C11.426 18.5 9.33333 16.426 9.33333 13.875C9.33333 11.324 11.426 9.25 14 9.25C16.574 9.25 18.6667 11.324 18.6667 13.875C18.6667 16.426 16.574 18.5 14 18.5Z"
                                  fill="#FFB23F" />
                        </svg>
                    </div>

                    <p class="w-full text-base lg:text-[30px]">Địa chỉ nhận hàng</p>
                </span>
                <span class="w-full flex items-center justify-between gap-x-3 lg:gap-x-5">
                    <p>
                        <strong class="text-sm lg:text-[25px]">@khachang.HoTen @khachang.Sdt</strong>
                    </p>
                    <p class="text-sm lg:text-[25px]">
                        10 CMT8, Phường 11, Quận Tân Bình, TP. Hồ Chí Minh
                    </p>
                    <p class="text-base lg:text-[25px] text-[#518581] cursor-pointer">
                        Thay đổi
                    </p>
                </span>
            </div>
            <div class="w-full">
                <!-- Title -->
                <div class="mb-[12px] px-[20px] shadow text-[14px] h-[55px] shadow items-center hidden lg:flex justify-center bg-[#fff]">
                    <div class="w-[calc(100%-58px)] lg:flex-1">
                        Sản phẩm
                    </div>
                    <div class="text-center w-[12.5%]">
                        Đơn giá
                    </div>
                    <div class="text-center  w-[12.5%]">
                        Số lượng
                    </div>
                    <div class="text-center  w-[12.5%]">
                        Thành tiền
                    </div>
                </div>

                <!-- Product 1 -->
                <div class="cart-info md:shadow">
                    @if (lsSanPham != null)
                    {
                        foreach (var item in lsSanPham)
                        {
                            <div class="border-b md:px-[20px] border-[rgba(0,0,0,0.09)] md:py-[15px] py-[5px] px-5  text-[14px] min-h-[55px] items-center flex  bg-[#fff] flex-wrap">
                                <div class="lg:flex-1">
                                    <a href="" class="flex">
                                        <div class="aspect-square min-w-[80px] max-h-[80px] rounded-[3px] ">
                                            <img class="object-cover h-full" src="@item.HinhAnh"
                                         alt="@item.TenSp">
                                        </div>
                                        <div class="ml-3 flex justify-between px-2 lg:px-0 flex-col gap-y-[3px] ">
                                            <span class="lg:text-[14px] md:max-w-[250px] line-clamp-2">
                                                @item.TenSp
                                            </span>

                                            <div class="md:hidden md:font-semibold flex justify-between">
                                                <span class="rate">@item.Gia.ToString("#,##0")đ</span>
                                                <span class="ml-[15px] quantity">x2</span>
                                                <!-- <input value="200000" type="number" class="amount"></input> -->
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <div class="hidden text-center lg:flex items-center justify-center color-orange font-semibold w-[12.5%]">
                                    <span class="rate">@item.Gia.ToString("#,##0")</span>đ
                                    <!-- <input value="200000" type="number" class="amount"></input> -->
                                </div>

                                <div class="num hidden text-center lg:w-[12.5%] lg:block text-[16px]" type="number" min="0" id="Quantity">
                                    @item.TongSl
                                </div>
                                @{
                                    double thanhtien = item.Gia * item.TongSl;
                                }
                                <div class="hidden text-center lg:flex items-center justify-center color-orange font-semibold w-[12.5%]">
                                    <span class="amount">@thanhtien.ToString("#,##0")</span>đ
                                            
                                    <!-- <input value="200000" type="number" class="amount"></input> -->
                                </div>

                            </div>

                        }
                    }
                </div>
            </div>
        </div>

        <div class="w-full flex items-center justify-end gap-x-[47px]">
        </div>
    </div>

    <div class="sticky bottom-0 bg-[#fff] border-dotted border-[rgba(0,0,0,.09)] lg:border  lg:py-2 lg:pr-6 lg:pl-[40px] pl-[10px] my-4 flex  items-center justify-between ">

        <!-- Thanh toán -->
        <div class="flex  text-[30px] gap-x-2 items-center">
            <div class="hidden md:block text-[16px]">
                Nhấn "Đặt hàng" đồng nghĩa với việc bạn đồng ý tuân theo Điều khoản
                BiSys
            </div>

        </div>
        <div class="result-cart flex items-center ">
            <div class="flex text-[30px] gap-x-2 items-center">
                <div class="text-[14px] lg:text-[16px]">Tổng thanh toán: </div>
                <span class="text-[18px] lg:text-[24px] text-[#ee4d2d] font-semibold">
                    <span class="sum-cart">@tongThanhTien</span>đ
                </span>
            </div>
        </div>

        <a asp-controller="Payment" asp-action="InsertHoaDon"
           class="ml-2 lg:ml-5 flex items-center rounded-[2px] text-white border bg-[#ee4d2d] h-[56px]  px-[10px] lg:px-[20px]  text-white text-[15px] lg:text-[24px] font-semibold">
            Đặt hàng
        </a>

    </div>
</main>